# render.yaml - Place in root of your repository
services:
  - type: web
    name: kenyavault-payment
    runtime: node
    repo: https://github.com/Sulman-P/kenyavault
    branch: main
    plan: free
    buildCommand: yarn install
    startCommand: node server.js
    envVars:
      - key: SMTP_USER
        value: kenyavault@gmail.com
      - key: SMTP_PASS
        value: tryp whij iihs krkn
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJld3BtaW5tcW5ydHdkdmdseHhyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTc0OTM5OSwiZXhwIjoyMDk3MzI1Mzk5fQ.qkL7O1o1dhf9jCFuIQIUyJWFUBaq404ePWU0X4I5p1k
      - key: SUPABASE_URL
        value: https://rewpminmqnrtwdvglxxr.supabase.co
      - key: MEGAPAY_API_KEY
        value: MGPYDSg2lIYA
      - key: MEGAPAY_EMAIL
        value: adminnexalearn@gmail.com
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
